apiVersion: apps/v1
kind: Deployment
metadata:
  name: apple
  namespace: beyla-target-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apple
  template:
    metadata:
      labels:
        app: apple
    spec:
      containers:
      - name: apple
        image: beyla-app-apple:v1
        ports:
        - containerPort: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: apple
  namespace: beyla-target-app
spec:
  selector:
    app: apple
  ports:
  - protocol: TCP
    port: 9000
    targetPort: 9000
