apiVersion: apps/v1
kind: Deployment
metadata:
  name: banana
  namespace: beyla-target-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: banana
  template:
    metadata:
      labels:
        app: banana
    spec:
      containers:
      - name: banana
        image: beyla-app-banana:v1
        ports:
        - containerPort: 9001
---
apiVersion: v1
kind: Service
metadata:
  name: banana
  namespace: beyla-target-app
spec:
  selector:
    app: banana
  ports:
  - protocol: TCP
    port: 9001
    targetPort: 9001
